import '../models/market_asset_model.dart';

class MultiMarketService {
  static List<MarketAssetModel> getGlobalAssets() {
    return [
      // 1. Metals
      MarketAssetModel(
        id: 'gold_ounce',
        symbol: 'XAU/USD',
        name: 'Gold (Ounce)',
        faName: 'انس طلای جهانی',
        market: MarketType.metals,
        categoryName: 'Precious Metals',
        faCategoryName: 'فلزات گران‌بها',
        exchange: 'OANDA',
        quoteAsset: 'USD',
        price: 2685.40,
        change24h: 0.84,
        unit: 'USD/oz',
        faUnit: 'دلار/اونس',
      ),
      MarketAssetModel(
        id: 'silver_ounce',
        symbol: 'XAG/USD',
        name: 'Silver (Ounce)',
        faName: 'انس نقره جهانی',
        market: MarketType.metals,
        categoryName: 'Precious Metals',
        faCategoryName: 'فلزات گران‌بها',
        exchange: 'OANDA',
        quoteAsset: 'USD',
        price: 31.85,
        change24h: 1.45,
        unit: 'USD/oz',
        faUnit: 'دلار/اونس',
      ),

      // 2. Energy
      MarketAssetModel(
        id: 'brent_crude',
        symbol: 'BRENT',
        name: 'Brent Crude Oil',
        faName: 'نفت خام برنت',
        market: MarketType.energy,
        categoryName: 'Commodities',
        faCategoryName: 'انرژی و سوخت',
        exchange: 'ICE',
        quoteAsset: 'USD',
        price: 74.50,
        change24h: -1.15,
        unit: 'USD/bbl',
        faUnit: 'دلار/بشکه',
      ),
      MarketAssetModel(
        id: 'wti_oil',
        symbol: 'WTI',
        name: 'Crude Oil WTI',
        faName: 'نفت خام وست تگزاس',
        market: MarketType.energy,
        categoryName: 'Commodities',
        faCategoryName: 'انرژی و سوخت',
        exchange: 'NYMEX',
        quoteAsset: 'USD',
        price: 70.80,
        change24h: -0.92,
        unit: 'USD/bbl',
        faUnit: 'دلار/بشکه',
      ),

      // 3. Forex
      MarketAssetModel(
        id: 'eur_usd',
        symbol: 'EUR/USD',
        name: 'Euro / US Dollar',
        faName: 'یورو / دلار آمریکا',
        market: MarketType.forex,
        categoryName: 'Major FX',
        faCategoryName: 'فارکس اصلی',
        exchange: 'FXCM',
        quoteAsset: 'USD',
        price: 1.0875,
        change24h: 0.12,
      ),
      MarketAssetModel(
        id: 'gbp_usd',
        symbol: 'GBP/USD',
        name: 'British Pound / US Dollar',
        faName: 'پوند انگلیس / دلار',
        market: MarketType.forex,
        categoryName: 'Major FX',
        faCategoryName: 'فارکس اصلی',
        exchange: 'FXCM',
        quoteAsset: 'USD',
        price: 1.3020,
        change24h: -0.18,
      ),
      MarketAssetModel(
        id: 'usd_jpy',
        symbol: 'USD/JPY',
        name: 'US Dollar / Japanese Yen',
        faName: 'دلار آمریکا / ین ژاپن',
        market: MarketType.forex,
        categoryName: 'Major FX',
        faCategoryName: 'فارکس اصلی',
        exchange: 'FXCM',
        quoteAsset: 'JPY',
        price: 151.60,
        change24h: 0.42,
      ),

      // 4. World Indices
      MarketAssetModel(
        id: 'sp500',
        symbol: 'S&P 500',
        name: 'S&P 500 Index',
        faName: 'شاخص ۵۰۰ شرکت برتر آمریکا',
        market: MarketType.indices,
        categoryName: 'US Indices',
        faCategoryName: 'شاخص‌های آمریکا',
        exchange: 'CBOE',
        quoteAsset: 'USD',
        price: 5865.0,
        change24h: 0.45,
      ),
      MarketAssetModel(
        id: 'nasdaq100',
        symbol: 'NASDAQ 100',
        name: 'Nasdaq 100 Tech Index',
        faName: 'شاخص ۱۰۰ شرکت فناوری نزدک',
        market: MarketType.indices,
        categoryName: 'US Indices',
        faCategoryName: 'شاخص‌های آمریکا',
        exchange: 'NASDAQ',
        quoteAsset: 'USD',
        price: 20450.0,
        change24h: 0.82,
      ),
      MarketAssetModel(
        id: 'vix_volatility',
        symbol: 'VIX',
        name: 'CBOE Volatility Index (Fear Index)',
        faName: 'شاخص نوسان و ترس وال‌استریت',
        market: MarketType.indices,
        categoryName: 'Volatility',
        faCategoryName: 'شاخص ترس و نوسان',
        exchange: 'CBOE',
        quoteAsset: 'USD',
        price: 18.25,
        change24h: -3.40,
      ),
      MarketAssetModel(
        id: 'dxy_dollar_index',
        symbol: 'DXY',
        name: 'US Dollar Index',
        faName: 'شاخص قدرت دلار جهانی',
        market: MarketType.indices,
        categoryName: 'Currency Index',
        faCategoryName: 'شاخص‌های ارزی',
        exchange: 'ICE',
        quoteAsset: 'USD',
        price: 104.15,
        change24h: 0.18,
      ),
      MarketAssetModel(
        id: 'dax40',
        symbol: 'DAX 40',
        name: 'Germany DAX 40',
        faName: 'شاخص داکس آلمان',
        market: MarketType.indices,
        categoryName: 'European',
        faCategoryName: 'بورس اروپا',
        exchange: 'XETRA',
        quoteAsset: 'EUR',
        price: 19480.0,
        change24h: 0.38,
      ),
      MarketAssetModel(
        id: 'nikkei225',
        symbol: 'NIKKEI 225',
        name: 'Nikkei 225 Japan',
        faName: 'شاخص نیکی ۲۲۵ ژاپن',
        market: MarketType.indices,
        categoryName: 'Asian',
        faCategoryName: 'بورس آسیا',
        exchange: 'TSE',
        quoteAsset: 'JPY',
        price: 38910.0,
        change24h: 1.15,
      ),

      // 5. Sovereign Bonds
      MarketAssetModel(
        id: 'us_10y_yield',
        symbol: 'US 10Y YIELD',
        name: 'US Treasury 10-Year Yield',
        faName: 'بازده اوراق ۱۰ ساله خزانه‌داری آمریکا',
        market: MarketType.bonds,
        categoryName: 'Sovereign Yields',
        faCategoryName: 'اوراق خزانه‌داری',
        exchange: 'CBOE',
        quoteAsset: '%',
        price: 4.28,
        change24h: -0.46,
        unit: '%',
        faUnit: 'درصد',
      ),
      MarketAssetModel(
        id: 'us_2y_yield',
        symbol: 'US 2Y YIELD',
        name: 'US Treasury 2-Year Yield',
        faName: 'بازده اوراق ۲ ساله آمریکا',
        market: MarketType.bonds,
        categoryName: 'Sovereign Yields',
        faCategoryName: 'اوراق خزانه‌داری',
        exchange: 'CBOE',
        quoteAsset: '%',
        price: 4.14,
        change24h: -0.24,
        unit: '%',
        faUnit: 'درصد',
      ),
      MarketAssetModel(
        id: 'german_bund_10y',
        symbol: 'GERMANY 10Y',
        name: 'Germany 10Y Bund Yield',
        faName: 'اوراق ۱۰ ساله آلمان (بوند)',
        market: MarketType.bonds,
        categoryName: 'European Bonds',
        faCategoryName: 'اوراق اروپا',
        exchange: 'EUREX',
        quoteAsset: '%',
        price: 2.34,
        change24h: 0.43,
        unit: '%',
        faUnit: 'درصد',
      ),

      // 6. Top Equities
      MarketAssetModel(
        id: 'nvda_nvidia',
        symbol: 'NVDA',
        name: 'NVIDIA Corporation',
        faName: 'سهام انویدیا (تراشه و AI)',
        market: MarketType.stocks,
        categoryName: 'AI & Chips',
        faCategoryName: 'هوش مصنوعی و تراشه',
        exchange: 'NASDAQ',
        quoteAsset: 'USD',
        price: 139.80,
        change24h: 2.45,
      ),
      MarketAssetModel(
        id: 'aapl_apple',
        symbol: 'AAPL',
        name: 'Apple Inc.',
        faName: 'سهام شرکت اپل',
        market: MarketType.stocks,
        categoryName: 'Big Tech',
        faCategoryName: 'فناوری',
        exchange: 'NASDAQ',
        quoteAsset: 'USD',
        price: 232.50,
        change24h: 0.65,
      ),
      MarketAssetModel(
        id: 'tsla_tesla',
        symbol: 'TSLA',
        name: 'Tesla, Inc.',
        faName: 'سهام تسلا (خودرو و رباتیک)',
        market: MarketType.stocks,
        categoryName: 'EV & Auto',
        faCategoryName: 'خودرو و رباتیک',
        exchange: 'NASDAQ',
        quoteAsset: 'USD',
        price: 220.40,
        change24h: -1.20,
      ),
      MarketAssetModel(
        id: 'mstr_microstrategy',
        symbol: 'MSTR',
        name: 'MicroStrategy Inc.',
        faName: 'میکرواستراتژی (پراکسی بیت‌کوین)',
        market: MarketType.stocks,
        categoryName: 'Crypto Equities',
        faCategoryName: 'سهام کریپتو',
        exchange: 'NASDAQ',
        quoteAsset: 'USD',
        price: 254.00,
        change24h: 5.80,
      ),
    ];
  }
}
